Bootstrap project
tzvaita/bootstrap-project pull request #1
Opened 2019-12-04 20:22 UTC by tzvaita

Site development completed

2019-12-04 20:55 UTC, pelzolga123 commented
## Hi @tzvaita 
### Your Pull Requests should have meaningful title and short summary. You can read about it [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)

This Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready!

If you have any questions or need help, you can message me on slack. *Happy coding*

2019-12-05 00:01 UTC, izaiasneto4 requested changes
### Hi @tzvaita. Your clone looks really good!  :clap:  You're almost there, let's just change this small thing and we're done :arrow_down: 

- [ ] The Newsweek brand at the footer of the page needs to be an actual image. (**Hint**: You can use an SVG image in this situation :wink: )
![image](https://user-images.githubusercontent.com/5157985/70191859-e04b4e00-16d8-11ea-9392-724cb5264c57.png)

### That's it! When finished, please re-submit your project for a new review :pray: 

TSE: Izaias Neto

2019-12-05 04:12 UTC, Oluwadamilareolusakin commented
# Fantastic work! :rocket: 
Please merge and remember to bring the same energy and attention to detail in your other projects :smile:, see you at the top! :handshake:

2019-12-05 04:13 UTC, nikasulo approved these changes

2019-12-05 08:11 UTC, merged